In [3]:
import pandas as pd

# create data
states = ['Texas', 'Rhode Island', 'Nebraska'] # string
population = [27.86E6, 1.06E6, 1.91E6]         # float
electoral_votes = [38, 3, 5]                   # integer
is_west_of_MS = [True, False, True]            # Boolean

# create and display DataFrame
headers = ('State', 'Population', 'Electoral Votes', 'West of Mississippi')
data = (states, population, electoral_votes, is_west_of_MS)
data_dict = dict(zip(headers, data))

df1 = pd.DataFrame(data_dict)
df1

State  Population  Electoral Votes  West of Mississippi
0         Texas  27860000.0               38                 True
1  Rhode Island   1060000.0                3                False
2      Nebraska   1910000.0                5                 True

In [7]:
print(df1['Population'])

0    27860000.0
1     1060000.0
2     1910000.0
Name: Population, dtype: float64


In [9]:
print (type(df1['Electoral Votes'].iloc[0]))
print (type(df1['Population'].iloc[0]))
print (type(df1['West of Mississippi'].iloc[0]))

<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.bool_'>


NameError: name 'np' is not defined

In [13]:
import numpy as np

X = np.random.random((4, 2))  # create random 4x2 array
y = np.cos(X)                 # take the cosine on each entry of X

print (y)
print ("\n The dimension of y is"), y.shape

[[0.97367275 0.54543193]
 [0.76010592 0.89208455]
 [0.87229172 0.81276944]
 [0.54957805 0.65289393]]

 The dimension of y is


(None, (4, 2))

In [15]:
print (y[0, :])   # select 1st row
print (y[:, 1] )  # select 1st column
print (y[2, 1])   # select element y_12
print (y[1:2, :]) # select rows 2nd and 3rd row

[0.97367275 0.54543193]
[0.54543193 0.89208455 0.81276944 0.65289393]
0.8127694422755751
[[0.76010592 0.89208455]]


In [16]:
df2 = pd.DataFrame({"times": [1.0, 2.0, 3.0, 4.0], "more times": [5.0, 6.0, 7.0, 8.0]})
df2 = np.cos(df2)
df2.head()

times  more times
0  0.540302    0.283662
1 -0.416147    0.960170
2 -0.989992    0.753902
3 -0.653644   -0.145500

In [17]:
df1.groupby('West of Mississippi').agg('max')

State  Population  Electoral Votes
West of Mississippi                                           
False                Rhode Island   1060000.0                3
True                        Texas  27860000.0               38